### ISSUE TITLE
hook_config_info() should not include ".json"

### ISSUE THREAD

**Issue by quicksketch** [JugglingCoder/spam_bot_blocker#1]
The `hook_config_info()` implementation should not include ".json" in the $prefixes list. Long-term, Backdrop may store config in ways other than JSON files, so this extension is not included. Likewise, other places where you load/save config, the JSON extension is excluded. It looks like only the hook_config_info() does this however:

```
  $prefixes['spam_bot_blocker.settings.json'] = array(
    'label' => t('Spam Bot Blocker Settings'),
    'group' => t('Configuration'),
  );
```

So just remove the `.json` from `spam_bot_blocker.settings.json`. Try testing the export of configuration under `admin/config/development/configuration` to make sure it works.

**Comment by JugglingCoder** [comment]
removed the .json from spam_bot_blocker.settings.json in function: spam_bot_blocker_config_info.  Tested export under config export and working

**Comment by quicksketch** [comment]
Super, thanks!
